# Architecture
arch: mnist_conv

# ===== Dataset ===== #
data: dataset/
set: FashionMNIST
name: probmask

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.001
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0
batch_size: 1000

# ===== Sparsity =========== #
conv_type: ProbMaskConv
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
prune_rate: 0.1
iterative: True

# ===== Hardware setup ===== #
workers: 4