# Architecture
arch: resnet32

# ===== Dataset ===== #
data: dataset/
set: CIFAR10
name: probmask

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.006
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 300
weight_decay: 0
batch_size: 256

# ===== Sparsity =========== #
conv_type: ProbMaskConv
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
prune_rate: 0.1
iterative: True

# ===== Hardware setup ===== #
workers: 4